/**
 * @file pruning.cpp
 * @author Jan Jendrysiak and Fabian Lenzen
 * @brief
 * @version 0.1
 * @date 2025-03-13
 *
 * @copyright
 *
 */

#include "grlina/graded_matrix.hpp"
#include <grlina/graded_linalg.hpp>
#include <algorithm>
namespace stable_decomposition {

using namespace graded_linalg;
using index_t = int; // Change to large enough int type.
using Mat = R2GradedSparseMatrix<index_t>;

Mat submodule_sum(Mat l, Mat r){
    assert(l.row_degrees == r.row_degrees);
    l.append_matrix(std::move(r));
    auto nzc = l.column_reduction_graded();
    l.delete_all_but_columns(nzc);
    return l;
}

// H: Simplifies the presentation of S as a submodule of M. Check correctness.
Mat reduce_submodule(Mat S, Mat M){
    auto M_copy = M;
    M_copy.append_matrix(S);
    M_copy.column_reduction_graded();
    auto nzc = M_copy.column_reduction_graded();
    int n = M.get_num_cols();
    for(int i = nzc.size()-1; i >= 0; --i){
        if(nzc[i] < n){
            nzc.erase(nzc.begin()+i);
        }
    }
    M_copy.delete_all_but_columns(nzc);
    return M_copy;
}

Mat image(const Mat &f, const Mat &A, const Mat &B, const Mat &U){/// image of submodule U of A under morphism f: A -> B
    return f*U; //TODO not correct if submodules must be presented by minimal generating systems
};

vec<Mat> hom_space(Mat A, Mat B){
    return hom_space_basis<r2degree, int, Mat>(A, B); // returns a basis of Hom(A, B) as a vector of matrices
}; // basis of Hom(A, B); done by hom_space_basis

Mat shifting_morphism(Mat A, double delta){
    r2degree shift = {delta, delta};
    return shifted_identity<r2degree, Mat>(A.row_degrees, shift);
}; // canonical morphism M -> M(2delta)

Mat zero_submodule(const Mat &m); // 0 as submodule of M, likely unnecessary
Mat all_submodule(const Mat &m); // M as submodule of M, likely unnecessary

/// Return true of im M is contained in im N TO-DO: Relations implicitely ignored.
bool image_contained_in_image(const Mat &M, const Mat &N){
    auto N_copy = N; 
    int threshold =  N.get_num_cols();
    N_copy.append_matrix(M);
    N_copy.column_reduction_graded();
    bool is_zero = true;
    for(int i = threshold; i < N_copy.get_num_cols(); i++){
        if(N_copy.data[i].size() != 0){
            is_zero = false;
            break;
        }
    }
    return is_zero;
}

/// Checks if the two submodules generated by `A` and `B` of the module presented by `M` are isomorpic.
bool present_same_submodule(const Mat &M, const Mat &A, const Mat &B){
    Mat MA = M, MB = M;
    MA.append_matrix(A);
    MB.append_matrix(B);
    return image_contained_in_image(B, MA) && image_contained_in_image(A, MB);
}
/// Computes a pruning pair (I,K) of a module M given by presentation, following Bjerkevik 2025, Lemma 5.2
auto pruning_pair(const Mat &M, const double delta){
    // Build a presentation matrix for M(2δ)
    Mat M2d = M;
    M2d.shift({delta, delta});
    // Build a basis Γ for Hom(M, M(2δ)).
    vec<Mat> G; //TODO: make G a basis of hom_space(M, N);
    Mat can = shifting_morphism(M2d, delta); // TODO: build the canonical morphism M -> M(2d)

    // Build the module I from the pruning pair
    Mat I = all_submodule(M);
    for(;;){
        auto I_new = all_submodule(M);
        for(auto &&f : G)
            // (f \circ I_new)^{-1}(can*I);
            I_new = M.submodule_intersection(I_new, f.inverse_image(M2d, can * I));

        if(present_same_submodule(M, I_new, I)) //TODO implement
            break;
        std::swap(I, I_new);
    }
    Mat can_I; //TODO: the canonical morphism I -> I(2d)
    // Build the module K from the pruning pair
}
} // namespace stable_decomposition
