/**
 * @file pruning.cpp
 * @author Jan Jendrysiak and Fabian Lenzen
 * @brief
 * @version 0.1
 * @date 2025-03-13
 *
 * @copyright
 *
 */

#include "grlina/graded_matrix.hpp"
#include <grlina/graded_linalg.hpp>
#include <algorithm>
#include <filesystem>
namespace stable_decomposition {

using namespace graded_linalg;
using index_t = int; // Change to large enough int type.
using Mat = R2GradedSparseMatrix<index_t>;


Mat submodule_sum(Mat l, Mat r){
    assert(l.row_degrees == r.row_degrees);
    l.append_matrix(std::move(r));
    auto nzc = l.column_reduction_graded();
    l.delete_all_but_columns(nzc);
    return l;
}

// H: Simplifies the presentation of S as a submodule of M. Check correctness.
Mat reduce_submodule(Mat M, Mat S){
    auto M_copy = M;
    M_copy.append_matrix(S);
    M_copy.column_reduction_graded();
    auto nzc = M_copy.column_reduction_graded();
    int n = M.get_num_cols();
    for(int i = nzc.size()-1; i >= 0; --i){
        if(nzc[i] < n){
            nzc.erase(nzc.begin()+i);
        }
    }
    M_copy.delete_all_but_columns(nzc);
    return M_copy;
}

Mat image(const Mat &f, const Mat &A, const Mat &B, const Mat &U){/// image of submodule U of A under morphism f: A -> B
    return f*U; //TODO not correct if submodules must be presented by minimal generating systems
};

vec<Mat> homSpace(Mat A, Mat B){
    //H: why does it allow me to compute rows forward when A is const where I'm calling homSpace??
	A.compute_rows_forward();
    return hom_space_basis<r2degree, int, Mat>(A, B); // returns a basis of Hom(A, B) as a vector of matrices
}; // basis of Hom(A, B); done by hom_space_basis

Mat shifting_morphism(Mat A, double delta){
    r2degree shift = {delta, delta};
    Mat result(A.get_num_rows(),A.get_num_rows(), "Identity");
    result.col_degrees = A.row_degrees;
    result.row_degrees = A.row_degrees;
    for(auto& g : result.row_degrees){
        g = g - shift;
    }
    return result;
    //return shifted_identity<r2degree, Mat>(A.row_degrees, shift);
}; // canonical morphism M -> M(2delta)

Mat zero_submodule(const Mat &m){
    Mat zero(0, m.get_num_rows()); // Create a zero submodule of M
    zero.row_degrees = m.row_degrees; // Ensure the row degrees match
    zero.col_degrees = vec<r2degree>(); // No columns, so no degrees 
    zero.data = vec<vec<int>>(); // No data, so empty vector
    return zero;
}; // 0 as submodule of M, likely unnecessary

Mat all_submodule(const Mat &m){
    Mat Id(m.get_num_rows(), m.get_num_rows(), "Identity");
    Id.row_degrees = m.row_degrees; // Ensure the row degrees match
    Id.col_degrees = m.row_degrees; // Ensure the column degrees match
    return Id;
}; // M as submodule of M, likely unnecessary

/// Return true of im M is contained in im N TO-DO: Is this correct? Relations implicitely ignored.
bool image_contained_in_image(const Mat &M, const Mat &N){
    auto N_copy = N; 
    int threshold =  N.get_num_cols();
    N_copy.append_matrix(M);
    N_copy.column_reduction_graded();
    bool is_zero = true;
    for(int i = threshold; i < N_copy.get_num_cols(); i++){
        if(N_copy.data[i].size() != 0){
            is_zero = false;
            break;
        }
    }
    return is_zero;
}

/// Checks if the two submodules generated by `A` and `B` of the module presented by `M` are isomorpic.
bool present_same_submodule(const Mat &M, const Mat &A, const Mat &B){
    Mat MA = M, MB = M;
    MA.append_matrix(A);
    MB.append_matrix(B);
    return image_contained_in_image(B, MA) && image_contained_in_image(A, MB);
}
/// Computes a pruning pair (I,K) of a module M given by presentation, following Bjerkevik 2025, Lemma 5.2
auto pruning_pair(const Mat &M, const double delta){
    // Build a presentation matrix for M(2δ)
    Mat M2d = M;
    // H: Shift seems to work by shifting the grades up, which gives the opposite of the positively shifted module
    M2d.shift({-delta, -delta});
    // Build a basis Γ for Hom(M, M(2δ)).
    vec<Mat> G = homSpace(M, M2d); 
    Mat can = shifting_morphism(M, delta);
    // Build the module I from the pruning pair
    // H: I is not in use right now, since we're not checking if I has been changed.
    Mat I_new = all_submodule(M);
    // H: Change 5 to something less arbitrary
    for(int i = 1; i <= 5; ++i){
        //auto I_new = all_submodule(M);
        for(const auto& f : G){
            // (f \circ I_new)^{-1}(can*I); This is implemented now.
            auto I_shifted = can * I_new;
            // TODO: The above just shifts the degrees of the generators, so we should do that directly and not multiply.
            auto f_copy = f;
            auto foI = f_copy * I_new;
            // H: I didn't get inverse_image to work, so I did it in here instead.
            foI.append_matrix(I_shifted);
            foI.append_matrix(M);
            auto K = foI.graded_kernel();
            K.cull_columns(I_new.get_num_cols(), false);
            K.column_reduction_graded();
            I_new = I_new * K;
            // H: without reduce_submodule, this gets suuuper slow
            I_new = reduce_submodule(M, I_new);
            //I_new = M.submodule_intersection(I_new, f_copy.inverse_image(M2d, I_shifted));
        }
        /*
        if(present_same_submodule(M, I_new, I)){
            break;
        }
        std::swap(I, I_new);*/
    }
    // Mat can_I; //TODO: the canonical morphism I -> I(2d)
    // Build the module K from the pruning pair
    return I_new; // Return the pruning pair (I, K)
}

} // namespace stable_decomposition

int main(){
    std::filesystem::path current_path = std::filesystem::path(__FILE__);
	std::filesystem::path example_path1 = current_path / "../Persistence-Algebra/test_presentations/toy_example_1.scc";
    using namespace stable_decomposition;
    R2GradedSparseMatrix<int> M(example_path1.string());
    M.print_graded();
    Mat I = pruning_pair(M, 1);
    I.print_graded();
    return 0;
}
